Reject change via configure hook

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -1,3 +1,8 @@
 #!/bin/bash
 
 # Placeholder to allow setting snap configurations
+
+if [ "$(snapctl get thread-if)" != "wpan0" ]; then
+    echo "Thread interface name cannot be configured as 'wpan0' has been hardcoded in setup scripts as well as the DBus policy"
+    exit 1
+fi
